server:
    port: 8081

spring:
    application:
            name: clientA
    thymeleaf:
        prefix: classpath:/static/

auth:
    callback: http://localhost:8081/auth/notify
    login: http://localhost:8080/login/loginPage
    checkAuth: http://localhost:8080/auth/checkAuth

eureka:
    client:
        serviceUrl:
            defaultZone: http://192.168.0.139:8080/eureka/
